openapi: 3.0.3
info:
  title: Events Calendar API
  version: 1.0.0
  description: API endpoints for managing and retrieving upcoming environmental events.

paths:
  /api/events:
    get:
      summary: Lists upcoming environmental events
      description: Fetches a list of upcoming environmental events, workshops, and conferences.
      parameters:
        - in: query
          name: category
          schema:
            type: string
          description: Optional category to filter events by specific themes.
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Limit the number of events returned. Defaults to 10.
      responses:
        '200':
          description: A list of events successfully retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
              example:
                - id: "e1"
                  title: "City Beach Clean-Up"
                  category: "Cleanup"
                  date: "2024-04-22"
                  location: "City Beach, Example City"
                  description: "Join us for a community beach clean-up event."
                - id: "e2"
                  title: "Renewable Energy Workshop"
                  category: "Workshop"
                  date: "2024-05-05"
                  location: "Green Tech Center, Example City"
                  description: "Workshop on the latest in renewable energy technology."
        '400':
          description: Bad request. Possible reason could be an invalid query parameter.

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the event.
        title:
          type: string
          description: Title of the event.
        category:
          type: string
          description: Category of the event.
        date:
          type: string
          format: date
          description: The date of the event.
        location:
          type: string
          description: Location where the event will take place.
        description:
          type: string
          description: A brief description of the event.
      required:
        - id
        - title
        - date
        - location
        - description
